server:
  port: 9999
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: springboot-swagger
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    default-property-inclusion: non_null
logging:
  config: classpath:logback-spring.xml
