server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 192.168.121.191:9300 # es的连接地址及端口号
      cluster-name: docker-cluster # es集群的名称
  elasticsearch:
    rest:
      uris: ["http://192.168.121.191:9200"]
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
# Timeout connecting to [localhost/127.0.0.1:9200]
#spring:
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: 192.168.10.68:9300
#  elasticsearch:
#    rest:
#      uris: ["http://192.168.10.68:9200"]
# 还有一种方式也可以解决,但是并不是一种好的解决方式,那就是关闭 actuator 对 elasticsearch 的健康检查
#management:
#  health:
#    elasticsearch:
#      enabled: false
